---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adel-speicher
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/speicher
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - adel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adel-speicher
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: adel-speicher
  resources:
    requests:
      storage: 100Gi
