apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
spec:
  template:
    spec:
      serviceAccountName: buildkitd
      containers:
      - name: tailscale-proxy
        image: ghcr.io/kasuboski/tailscale-proxy:main
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
        env:
          # Store the state in a k8s secret
        - name: KUBE_SECRET
          value: buildkitd-tailscale-state
        - name: HOSTNAME
          value: buildkitd
        - name: DEST_PORT
          value: "1234"
        - name: USERSPACE
          value: "false"
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: builder
              key: TAILSCALE_BUILDKITD_AUTH
              optional: false
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
