resources:
- sa.yaml
- deploy.yaml

patchesStrategicMerge:
- add-tailscale-proxy.yaml

configMapGenerator:
  - name: buildkitd-certs
    files:
      - ca.pem=root_ca.crt
      - cert.pem=buildkitd.crt
