apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkitd
  labels:
    app: buildkitd
    app.kubernetes.io/name: buildkitd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["buildkitd-tailscale-state"]
  resources: ["secrets"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "buildkitd"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
