apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: builder
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kasuboski/k8s-gitops.git
    targetRevision: main
    path: builder
  destination:
    server: https://kubernetes.default.svc
    namespace: builder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true